package alien4cloud.repository.model;

public enum ValidationStatus {
    SUCCESS, INVALID_REPOSITORY_URL, INVALID_REPOSITORY_TYPE, INVALID_CREDENTIALS, INVALID_ARTIFACT_REFERENCE, ARTIFACT_NOT_RETRIEVABLE
}
