require.config({
  baseUrl: './',
  paths: {
    'a4c-bootstrap': 'scripts/alien4cloud-bootstrap',
    'alien4cloud': 'scripts/alien4cloud',
    'states': 'scripts/utils/states_manager',
    'modules': 'scripts/utils/modules_manager',
    'plugins': 'scripts/utils/plugins_manager',
    'lodash': 'scripts/utils/alien_lodash',

    // bower_components
    'lodash-base': 'bower_components/lodash/lodash',
    'jquery': 'bower_components/jquery/dist/jquery',
    'angular': 'bower_components/angular/angular',
    'angular-cookies': 'bower_components/angular-cookies/angular-cookies',
    'angular-bootstrap': 'bower_components/angular-bootstrap/ui-bootstrap-tpls',
    'angular-resource': 'bower_components/angular-resource/angular-resource',
    'angular-sanitize': 'bower_components/angular-sanitize/angular-sanitize',
    'angular-ui-router': 'bower_components/angular-ui-router/release/angular-ui-router',
    'angular-translate-base': 'bower_components/angular-translate/angular-translate',
    'angular-translate': 'bower_components/angular-translate-loader-static-files/angular-translate-loader-static-files',
    'angular-animate': 'bower_components/angular-animate/angular-animate',
    'angular-xeditable': 'bower_components/angular-xeditable/dist/js/xeditable',
    'angular-ui-select': 'bower_components/angular-ui-select/dist/select',
    'angular-tree-control': 'bower_components/angular-tree-control/angular-tree-control',
    'ng-table': 'bower_components/ng-table/dist/ng-table',
    'toaster': 'bower_components/angularjs-toaster/toaster',
    'hopscotch': 'bower_components/hopscotch/dist/js/hopscotch',
    'angular-file-upload-shim': 'bower_components/ng-file-upload/angular-file-upload-shim',
    'angular-file-upload': 'bower_components/ng-file-upload/angular-file-upload',
    'button-confirm': 'bower_components/fc-angular-utils/button-confirm/button-confirm',
    'angular-ui-ace': 'bower_components/angular-ui-ace/ui-ace',
    'ace': 'bower_components/ace-builds/src-min-noconflict/ace',
    'sockjs': 'bower_components/sockjs/sockjs',
    'stomp': 'bower_components/stomp-websocket/lib/stomp',
    'd3': 'bower_components/d3/d3',
    'd3-tip': 'bower_components/d3-tip/index',
    'dagre': 'bower_components/dagre/dist/dagre.core',
    'dagre-d3': 'bower_components/dagre-d3/dist/dagre-d3.core',
    'd3-pie': 'bower_components/d3pie/d3pie/d3pie',
    'graphlib': 'bower_components/graphlib/dist/graphlib.core'
  },
  shim: {
    'angular': {
      deps: ['jquery'],
      exports: 'angular'
    },
    'angular-cookies': { deps: ['angular'] },
    'angular-bootstrap': { deps: ['angular'] },
    'angular-resource': { deps: ['angular'] },
    'angular-sanitize': { deps: ['angular'] },
    'angular-ui-router': { deps: ['angular'] },
    'angular-translate-base': { deps: ['angular'] },
    'angular-translate': { deps: ['angular-translate-base'] },
    'angular-all': { deps: ['angular-cookies', 'angular-translate', 'angular-ui-router', 'angular-sanitize', 'angular-resource', 'angular-bootstrap', 'angular-cookies'] },
    'ng-table': { deps: ['angular'] },
    'toaster': { deps: ['angular-animate'] },
    'angular-animate': { deps: ['angular'] },
    'angular-xeditable': { deps: ['angular'] },
    'angular-ui-select': { deps: ['angular'] },
    'angular-file-upload': { deps: ['angular', 'angular-file-upload-shim'] },
    'button-confirm': { deps: ['angular'] },
    'angular-ui-ace': { deps: ['angular', 'ace'] },
    'angular-tree-control': { deps: ['angular'] },
    'stomp':  { deps: ['sockjs'] },
    'graphlib': { deps: ['lodash-base'] },
    'dagre': { deps: ['graphlib'] },
    'dagre-d3': { deps: ['lodash-base', 'graphlib', 'dagre', 'd3'] },
    'd3-pie': { deps: ['d3'] }
  }
});
