package alien4cloud.topology.task;

public enum TaskCode {
    IMPLEMENT,
    IMPLEMENT_RELATIONSHIP,
    REPLACE,
    SATISFY_LOWER_BOUND,
    PROPERTIES,
    HA_INVALID,
    SCALABLE_CAPABILITY_INVALID,
    NODE_FILTER_INVALID,
    WORKFLOW_INVALID,

    INPUT_ARTIFACT_INVALID,
    ARTIFACT_INVALID,

    /* Location policies */
    LOCATION_POLICY,
    LOCATION_UNAUTHORIZED,
    LOCATION_DISABLED,

    ORCHESTRATOR_PROPERTY,
    INPUT_PROPERTY,
    NODE_NOT_SUBSTITUTED,

    FORBIDDEN_OPERATION
}
