package alien4cloud.paas.model;

import alien4cloud.deployment.model.SecretProviderConfigurationAndCredentials;
import alien4cloud.model.deployment.Deployment;
import alien4cloud.model.deployment.DeploymentTopology;
import lombok.*;

@Getter
@Setter
@ToString
@AllArgsConstructor(suppressConstructorProperties = true)
@NoArgsConstructor
public class PaaSDeploymentContext {

    private Deployment deployment;

    private DeploymentTopology deploymentTopology;

    private SecretProviderConfigurationAndCredentials secretProviderConfigurationAndCredentials;

    /**
     * Id to be used by the orchestration technology (PaaS) for the deployment.
     * 
     * @return Id to be used by the orchestration technology (PaaS) for the deployment.
     */
    public String getDeploymentPaaSId() {
        return deployment.getOrchestratorDeploymentId();
    }

    /**
     * Alien's technical deployment id. For events that are generated by PaaS, this id must be used instead of PaaS id
     * 
     * @return Alien's technical deployment id
     */
    public String getDeploymentId() {
        return deployment.getId();
    }

}
