package alien4cloud.paas.model;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import org.elasticsearch.annotation.ESObject;

import alien4cloud.model.deployment.Deployment;
import alien4cloud.model.deployment.DeploymentTopology;

@Getter
@Setter
@ToString
@AllArgsConstructor(suppressConstructorProperties = true)
@NoArgsConstructor
public class PaaSDeploymentContext {

    private Deployment deployment;

    private DeploymentTopology deploymentTopology;

    /**
     * Id to be used by the orchestration technology (PaaS) for the deployment.
     * 
     * @return Id to be used by the orchestration technology (PaaS) for the deployment.
     */
    public String getDeploymentPaaSId() {
        return deployment.getOrchestratorDeploymentId();
    }

    /**
     * Alien's technical deployment id. For events that are generated by PaaS, this id must be used instead of PaaS id
     * 
     * @return Alien's technical deployment id
     */
    public String getDeploymentId() {
        return deployment.getId();
    }
}
