package alien4cloud.paas.ha;

public enum AllocationErrorCode {
    NODE_NOT_ALLOCATED,
    NODE_BELONG_TO_MULTIPLE_HA_GROUPS,
    NODE_HAS_VOLUME_NOT_IN_THE_SAME_ZONE,
    NODE_HAS_ALLOCATED_ZONE_NOT_IN_DEPLOYMENT_SETUP,
    ZONES_NOT_DISTRIBUTED_EQUALLY,
    CONFIGURATION_ERROR,
    UNKNOWN_ERROR
}
