package alien4cloud.topology.task;

public enum TaskCode {
    IMPLEMENT,
    REPLACE,
    COMPLETE,
    SATISFY_LOWER_BOUND,
    PROPERTIES,
    HA_INVALID,
    SCALABLE_CAPABILITY_INVALID,
    NODE_FILTER_INVALID,
    WORKFLOW_INVALID,
    LOCATION_POLICY,
    ORCHESTRATOR_PROPERTY,
    INPUT_PROPERTY,
    NODE_NOT_SUBSTITUTED
}
