package alien4cloud.audit.model;

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@ToString
@EqualsAndHashCode
public class Method {

    /**
     * The signature generated by calling <code>java.lang.reflect.Method.toString()</code> on the controller method.
     */
    private String signature;

    private String method;

    private String category;

    private String action;

    private String[] bodyHiddenFields;
}
